name: ci-all_version

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  CI_on_PR:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertags: [
          latest,
          jazzy-ex1.18.2-otp27.2.4,
          jazzy-ex1.17.3-otp27.2.4,
          jazzy-ex1.16.3-otp26.2.5,
          humble-ex1.18.2-otp27.2.4,
          humble-ex1.17.3-otp27.2.4,
          humble-ex1.16.3-otp26.2.5,
        ]
    container: rclex/rclex_docker:${{ matrix.dockertags }}

    steps:
      - name: Checkout rclex repo
        uses: actions/checkout@v4
        with:
          repository: rclex/rclex
          path: rclex

      - name: Checkout rclex_connection_tests repo
        uses: actions/checkout@v4
        with:
          repository: rclex/rclex_connection_tests
          path: rclex_connection_tests

      - name: Retrieve cached dependencies
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            rclex/deps
            rclex/_build
          key: ${{ runner.os }}-${{ matrix.dockertags }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dockertags }}-mix-

      - name: Build dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: mix format
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix format --check-formatted

      - name: mix test
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex
          mix local.hex --force
          mix rclex.gen.msgs
          mix test

      - name: connection tests
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          cd rclex_connection_tests
          mix local.hex --force
          ./run-all.sh
